name: AI6127-proj
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - torchtext=0.14.1
  - torchmetrics=0.11.4
  - spacy=3.5.1
  - spacy-model-en_core_web_sm=3.5.0
  - nltk=3.8.1
  - lxml=4.9.2
  - beautifulsoup4=4.12.0
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - matplotlib=3.7.1